### ISSUE TITLE
[BUG] CastSpellByName(spellName, GUID | "mouseover") can not take effect

### ISSUE THREAD

**Issue by jilinge2** [balakethelock/SuperWoW#12]
CastSpellByName(spellName, GUID)
CastSpellByName(spellName, "mouseover")

I have tested those commands using both plugins and macro commands, but none of them take effect; they only cast on the current target.

**Comment by balakethelock** [comment]
Can't reproduce, tested the macro `/run CastSpellByName("Healing Wave(Rank 5)", "mouseover")` on a shaman and it works

**Comment by jilinge2** [comment]
I found the reason, it's because another plugin has hooked the CastSpellByName function.
