### ISSUE TITLE
[QUESTION] How do I enable autoloot?

### ISSUE THREAD

**Issue by Schockgeber** [balakethelock/SuperWoW#16]
The wiki doesn't really help me to understand how to set autoloot.

I tried the following combinations: 
/run SetAutoloot(1)
/run SetAutoloot 1
/run ("SetAutoloot", "1") 
/run Set("Autoloot", "1") 

but that did nothing at all.

**Comment by balakethelock** [comment]
https://github.com/balakethelock/SuperAPI/blob/0fb2da2d524035eae8f3d64956a993787789ea27/SuperAPI.lua#L64
