### ISSUE TITLE
[SUGGESTION] Add wowreeb section to "Compatibility with other mods"

### ISSUE THREAD

**Issue by veechs** [balakethelock/SuperWoW#2]
I've tested SuperWoW with [wowreeb](https://github.com/namreeb/wowreeb) and it works great. Here are instructions for the [Compatibility with other mods](https://github.com/balakethelock/SuperWoW/wiki/Compability-with-other-mods) wiki page.

## wowreeb:

If you're already using the [wowreeb](https://github.com/namreeb/wowreeb) launcher, loading SuperWoW is easy. Just add this line to the `<Realm>` section of the wowreeb config file (editing the path appropriately):

```xml
<DLL Path="path\to\SuperWoW\SuperWoWhook.dll" />
```

You can leave the `<DLL />` tags for VanillaFixes and/or nampower if you're using them, as SuperWoW won't conflict.

**Comment by balakethelock** [comment]
Thank you very much [54e5169](https://github.com/balakethelock/SuperWoW/wiki/Compability-with-other-mods/54e516905f32db8aacc971f5cfd9cec50dbf3acc)
