### ISSUE TITLE
[BUG] Berserking buff appears on Troll players when hit and refreshes duration every time you are hit.

### ISSUE THREAD

**Issue by apav** [balakethelock/SuperWoW#22]
**Describe the bug**
When using SuperWoW, a Berserking buff with an ID of 23303 appears on Troll players when hit, which lasts for 5 seconds and refreshes its duration every time you are hit.

**To Reproduce**
1. Get hit as a Troll player. 

**Expected behavior**
This buff should be completely invisible to SuperWoW and thus not visible to the player. 

**Screenshots**
![berserking](https://github.com/user-attachments/assets/d9bed698-0931-4f61-a13b-1548cc34c097)

**Additional context**
Happens on Turtle WoW

**Comment by balakethelock** [comment]
If SuperWoW makes a buff visible that shouldn't exist at all, then that's a bug with that specific server.
99% of dummy spells that SuperWoW exposes are bugs with the server, classic never sent them because they are not seen in any sniffs and thus it's up to that server to remove them.
