### ISSUE TITLE
[SUGGESTION]  add SetSize compatibility

### ISSUE THREAD

**Issue by shikulja** [balakethelock/SuperWoW#38]
like in modern client
vanilla supports only separated size
SetWidth
SetHeight

**Comment by balakethelock** [comment]
What? just use SetScale?

**Comment by shikulja** [comment]
?
vanilla support only SetWidth//SetHeight for set size
and not support SetSize - throw error
I wish I didn't have to think about it

**Comment by balakethelock** [comment]
```lua
function SetSize(frame, width, height)
  frame:SetWidth(width)
  frame:SetHeight(height)
end
```
You can put this in your code to add the function

**Comment by shikulja** [comment]
Well.. I’ll declare this function globally.. This will probably be a simple way.
