### ISSUE TITLE
[BUG] Player character targeting occasionally buggy

### ISSUE THREAD

**Issue by RUTHINAS** [balakethelock/SuperWoW#4]
**Describe the bug**
Every now and then I come across a player character that can not be targeted regularly. Clicking on the character will select them as a target, and any spell casts will act normally, but the target frame will not be displayed. Additionally, the tooltip when hovering over the character will display as if the character was a world object (like a bonfire or a signpost), meaning that TinyTip does not alter the tooltip in any way like it does for all other characters.

Relogging fixes it for the individual character in question, but typically another character close by has the same feature. It seems that the affected character is always someone near the player when logging in. Reloading the UI has _no effect_, the same characters seem to retain the bug after reload. The affected characters do not seem to share any specific traits with one another.

**Expected behavior**
Targeting should behave normally for all characters.

**Additional context**
The issue appeared with the introduction of SuperWoW & VanillaTweaks to my setup. Beyond that no other changes have been made.

![irregular targeting](https://github.com/balakethelock/SuperWoW/assets/94254826/85c444db-31c1-4788-a5d1-141a8a8eb6dd)
Here you see a character with the described behavior: regular tooltip (i.e. without addon features from TinyTip), no target frame (should be at the bottom of the screenshot). Of note is that the character's target-of-target **is** displayed (bottom left).

![regular targeting](https://github.com/balakethelock/SuperWoW/assets/94254826/33e7424d-5d0a-430c-9a42-0f2673827960)
Here you see a character without the bug. Tooltip has all the TinyTip features, target frame is visible, target-of-target is shown when applicable (not the case in the attached screenshot).

**Comment by balakethelock** [comment]
What do normal functions that can take "Target" argument for these players, for example what happens why you do /print UnitName("target")
Same question if you mouseover them & type UnitName("mouseover") or invite them to party & type UnitName("party1")

**Comment by RUTHINAS** [comment]
Seems to happen with players exclusively. I didn't get a chance to test very thoroughly yet, but a macro that does a UnitExists("target") and a UnitIsFriendly("target","player") check fails to run on bugged targets.

Bad WDB data is not the issue, I have the client set up to never even create WDB caches – a lack of it could be the culprit, but it would nevertheless be a bug that has never happened before.

**Comment by RUTHINAS** [comment]
I grouped with a player character that was displaying the bug. While not in party, the target frame did not become visible, and it stayed invisible after the player accepted the party invite. However, retargeting fixed that and the target frame behaved normally from then on, until I disbanded the party and it was reverted to its bugged behavior. Additionally, the party frames worked perfectly well from the start.

In this case the target was from the opposite faction, but that has not been the case for all characters exhibiting the bug.

**Comment by balakethelock** [comment]
https://github.com/balakethelock/SuperWoW/releases/tag/Release

Hopefully this release fixes it

**Comment by liaochaofeng** [comment]
The problem has been there for a long time, and I hope to fix the bug
![Uploading WoWScrnShot_061124_223549.jpg…]()

**Comment by Platinumcoated** [comment]
https://www.youtube.com/watch?v=wq9vdF7ut74
experienced this myself
using SuperWoW + VanillaTweaks, loads of addons
raid frames are Luna - all my healing spells are mousover macros  - /lunamo Healing Touch - these macros are provided by Luna

**Comment by Platinumcoated** [comment]
more info:
During a battleground one enemy player was bugged in this way, but after I died and came back into the fight again targeting this player was fixed again.
Another time I was running around Searing Gorge and noticed another player exhibiting this bug, but after meeting them a second time a few minutes later it was fixed, targeting them worked fine.
- so in conclusion when a player gets out of range and is not loaded by the client anymore, the bug disappears

**Comment by balakethelock** [comment]
Fixed in 1.1.2
