### ISSUE TITLE
[BUG] Using CastSpellByName(SPELL, "mouseover") with some abilities changes your target

### ISSUE THREAD

**Issue by bhhandley** [balakethelock/SuperWoW#45]
**Describe the bug**
Came across this while QA testing targeting logic in my addon.  Using CastSpellByName with a mouseover target will cause you to change targets if you have not attacked the first and phantom change targets if you have attacked it.  Meaning your target and selection circle will show as the original target but you are no longer attacking that target.  Tested with Hamstring, Pummel, Intercept, Shield Bash, Sunder Armor, Rend, Slam and Taunt.

Taunt was the only ability I tried that worked as expected.  I'm sure there are more and I also didn't test other classes but I have not noticed any issues with mouseover casting on my druid or priest and just happened to come across this.

**To Reproduce**
1. Target one enemy unit (Apprentice Target Dummy)
2. Attack the unit
3. Use CastSpellByName(SPELL, "mouseover") either in a macro or an addon
4. Your target will still show as the first however your actual target is the mouseover target
5. If you do not attack the original target, your target will fully change to the mouseover target

**Expected behavior**
Cast the spell on the mouseover target while maintaining my current target.

**Screenshots**
[Video Here](https://youtu.be/EaVfdt8Kg8k)

**Additional context**
Happened on Turtle Wow.  Only superwow, and AddOnOrganizer loaded.

**Comment by balakethelock** [comment]
Interesting behavior, I didn't know autoattacking a unit that isn't your target is possible even server-side.

Taunt is a spell, the others are physical weapon swings, so it makes sense that this would excluse taunt. Personally I never tested mouseover casting with a warrior or rogue's abilities so it's the first time I see it. It's possible they are coded to start autoattacking the victim when they successfully cast, and that's causing the behavior you're seeing.

I wouldn't rush to call this bug, just a mouseover casting quirk. You can bypass it by doing "/startattack" with your mouseover cast macros to go back to autoattacking your main target.

**Comment by bhhandley** [comment]
Very interesting, I didn't think to try a startattack first.  If you don't think it's a superwow bug, feel free to close the issue.  I'll do some more testing, just surprised it hasn't come up before.  I would have thought mouseover hamstring/kicks/gouges/etc would be more common but I'm probably getting my decades mixed up.  Thanks for looking either way.

**Comment by bhhandley** [comment]
Outside of actually changing targets, I can't get any combination of actions to work if I've already taken a swing at the first target.  I've been messing with different targeting logic because of HealComm and whatnot so that could be part of it but I've tried a few different addons as well.  Could you share what you used if anything?  In any case, closing the issue as a Vanilla thing.

Thanks
