### ISSUE TITLE
[BUG] I do not know if this is due to the addon or the program itself, but capital letters in the frame names have been converted to lowercase.

### ISSUE THREAD

**Issue by jilinge2** [balakethelock/SuperWoW#7]
addon 1 address: https://github.com/Sentilix/capslock
addon 2 address: https://github.com/gnwl/NotGrid

When I enable only addon 1 or addon 2 separately, this problem does not occur. However, after enabling both simultaneously, the frame name "CapslockFrameSummonQueueEntry1Target" in addon 1 has changed to "CapslockFrameSummonQueueEntry1**target**", , which causes an error in addon 1 and makes it unusable.
Error message: Interface\AddOns\Capslock\Capslock.lua:1217: attempt to index a nil value

If the frame name in addon 1 is changed to lowercase, there will be no error, and the addon will be usable.

**Comment by balakethelock** [comment]
Thanks for helping narrow down the issue, it will be fixed in version 1.2

**Comment by jilinge2** [comment]
When passing arguments to a function, if the value of the argument is the string "Target", the value received by the function that accepts the argument is changed to lowercase "target".

**Comment by balakethelock** [comment]
https://github.com/balakethelock/SuperWoW/releases/tag/Release

Try if this release fixes it
